version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: order-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_management_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order-management
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_ready -U order_user -d order_management_db']
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
