version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: order-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: order-management
      MYSQL_DATABASE: order_management_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order-management
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
